**Email Address: farhanbinrabbani@gmail.com**

In [1]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


**Answer to Question: 1.**

In [2]:
#Q1. Create NumPy arrays from the ages and salaries data generated above.
#Print both arrays and display their dtype, ndim, shape, and size.

age_arr = np.array(ages)
sal_arr = np.array(salaries)

print(age_arr)
print(f"Age dtype: {age_arr.dtype}")
print(f"Age ndim: {age_arr.ndim}")
print(f"Age shape: {age_arr.shape}")
print(f"Age size: {age_arr.size}")

print()

print(sal_arr)
print(f"Salary dtype: {sal_arr.dtype}")
print(f"Salary ndim: {sal_arr.ndim}")
print(f"Salary shape: {sal_arr.shape}")
print(f"Salary size: {sal_arr.size}")

[56 46 32 25 38 56 36 40 28 28]
Age dtype: int32
Age ndim: 1
Age shape: (10,)
Age size: 10

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Salary dtype: int32
Salary ndim: 1
Salary shape: (10,)
Salary size: 10


**Answer to Question: 2.**

In [3]:
#Q2. Using the salaries array, find and print the highest and lowest salary values.
#Also, calculate and print the average salary and age using NumPy functions.

max = np.max(sal_arr)
min = np.min(sal_arr)
avg_sal = np.mean(sal_arr)
avg_age = np.mean(age_arr)

print(f"Highest salary: {max}, Lowest salary: {min}, Average salary: {avg_sal}, Average age: {avg_age}]")

Highest salary: 89735, Lowest salary: 30769, Average salary: 57446.9, Average age: 38.5]


**Answer to Question: 3.**

In [4]:
#Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition.
#Then count and print how many employees are older than 30.

greater_30 = age_arr[age_arr > 30]
print(greater_30)
print()

print(f"No. of employees older than 30: {len(greater_30)}")

[56 46 32 38 56 36 40]

No. of employees older than 30: 7


**Answer to Question: 4.**

In [13]:
#Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array).
#Print the new updated ages array.

incage_5 = age_arr + 5
print(f"New Ages Array: {incage_5}")
print()

print(f"Original Array: {age_arr}")

New Ages Array: [61 51 37 30 43 61 41 45 33 33]

Original Array: [56 46 32 25 38 56 36 40 28 28]


**Answer to Question: 5.**

In [6]:
#Q5. Using NumPy, calculate the total salary expense (sum of all salaries)
#and the difference between the maximum and minimum salary. Print both results.

print(f"Total salary expense: {np.sum(sal_arr)}")
print()

print(f"Difference between max and min salary = {max - min}")

Total salary expense: 574469

Difference between max and min salary = 58966


**Answer to Question: 6.**

In [7]:
#Q6. Load the employees.csv file into a Pandas DataFrame.
#Display the first 5 rows, and check basic info using info() and summary statistics using describe().

empdf = pd.read_csv('employees.csv')

print(empdf.head(5))
print()

print(empdf.info())
print()

print(empdf.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


**Answer to Question: 7.**

In [8]:
#Q7. Display only the id, age, and salary columns.
#Then show the last 3 rows using tail().

print(empdf.loc[:,['id', 'age', 'salary']])
print()

print(empdf.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR


**Answer to Question: 8.**

In [9]:
#Q8. Filter the DataFrame to show only employees who work in the IT department.
#Print the result and show the total number of IT employees.

short_empdf = empdf.loc[empdf['dept'] == 'IT']
print(short_empdf)

emp_no = len(short_empdf.index)
print()
print(f"Total number of IT employees: {emp_no}")

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

Total number of IT employees: 3


**Answer to Question: 9.**

In [10]:
#Q9. Sort the DataFrame by salary in descending order
#and display the top 3 highest-paid employees along with their department and age.

sal_empdf = empdf.sort_values('salary', ascending = 0)
print(sal_empdf.loc[:, ['id', 'dept', 'age']].head(3))

   id     dept  age
6   7  Finance   36
7   8       IT   40
0   1       HR   56


**Answer to Question: 10.**

In [11]:
#Q10. Replace all salary values greater than 80000 with 80000 using loc.
#Then calculate and print the new average salary of all employees after replacement.

empdf.loc[empdf['salary'] > 80000, 'salary'] = 80000

print(f"New average salary of employees: {empdf['salary'].mean()}")

New average salary of employees: 55863.3
