### NUMPY 2

In [23]:
import numpy as np 

arr = np.random.randint(1, 100, size=(10,5)) # sample - 10 , feature - 5
print(arr.shape)

(10, 5)


In [24]:
b = arr.reshape(5,10)
print(b.shape)
print(b.ndim) 
b

(5, 10)
2


array([[38,  5, 93, 53, 38, 88, 28, 75, 65, 26],
       [47,  5, 38, 56,  3, 55, 15, 31, 58, 36],
       [68, 15, 40, 85, 86, 65, 50, 75, 65, 36],
       [95, 87, 56, 57, 10, 82, 30,  4, 98,  1],
       [16, 64, 19,  2, 89, 56, 26, 36, 41, 13]], dtype=int32)

In [61]:
flatten = b.flatten()

print(flatten.ndim)
print(flatten) 

column_wise_flattening = np.ravel(b,order = 'F') #C dile row wise flattening kore
print(column_wise_flattening)

1
[38  5 93 53 38 88 28 75 65 26 47  5 38 56  3 55 15 31 58 36 68 15 40 85
 86 65 50 75 65 36 95 87 56 57 10 82 30  4 98  1 16 64 19  2 89 56 26 36
 41 13]
[38 47 68 95 16  5  5 15 87 64 93 38 40 56 19 53 56 85 57  2 38  3 86 10
 89 88 55 65 82 56 28 15 50 30 26 75 31 75  4 36 65 58 65 98 41 26 36 36
  1 13]


### CONCATENATION

In [62]:
c = np.random.randint(1, 10, size = (2,3))
d = np.random.randint(20, 30, size = (2,3))
print(c)
print(d)

con_row = np.concatenate((c,d),axis=0) #column number same thake, niche 2ta row ashe 
print(con_row)
con_col = np.concatenate((c,d), axis = 1) #row number same thake, pashe column add hoy
print(con_col)

[[6 2 4]
 [6 9 3]]
[[28 26 22]
 [25 22 24]]
[[ 6  2  4]
 [ 6  9  3]
 [28 26 22]
 [25 22 24]]
[[ 6  2  4 28 26 22]
 [ 6  9  3 25 22 24]]


In [28]:
# error 

# row-wise concatenate korar shomoi column same thakbe 
# col-wise concatenate korar shomoi row same thakbe 

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
print(r)
r = np.concatenate((x,y),axis =1 )
print(r)

[[3 9 8]
 [1 5 6]
 [9 1 3]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [29]:
# transpose 

mat = np.array([[10,20,30],
                [30,40,50]
               ])

transpose = mat.T
print(transpose) 

[[10 30]
 [20 40]
 [30 50]]


In [30]:
# array split 

a = np.random.randint(1 ,10 , size =(10,))
print(a)

splitted_array = np.array_split(a,3) 
print(splitted_array)

# split -> equal division 
splitted_array = np.split(a,3) 

[5 3 3 4 4 1 6 7 4 9]
[array([5, 3, 3, 4], dtype=int32), array([4, 1, 6], dtype=int32), array([7, 4, 9], dtype=int32)]


ValueError: array split does not result in an equal division

### ARITHMETIC OPERATIONS AND MATHEMATICAL FUNCTIONS

In [31]:
#check numpy mathematical functions online

# faster for vectorization

x = np.array([ 10, 8, 30, 100 ])
y = np.array([ 2, 3, 4, 5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x%y
print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [32]:
# mathematical function 

# trigonometry -> sin, cos, tan take values in radians 

sin_val = np.sin(x)
print(sin_val) 

cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)
# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [33]:
#log 

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [35]:
#different sum
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [38]:
#broadcasting 

x = np.array([ 10 , 8 , 16 , 100 ])
result = x + 2 # a scalar broadcasted throughou the array

#rulings = columns er size and vector er size same hote hobe 

matrix = np.array([[10,20,30],
                [30,40,50]
               ])
result = matrix + 2

vector = np.array([1,2,3]) 
result = matrix + vector # vector broadcasted along matrix
print(result)

[[11 22 33]
 [31 42 53]]


### LOGICAL FUNCTIONS

In [39]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = x>y 
print(greater_than)

equal = x==y 
print(equal) 

# all () -> shob true kina 
# any() -> jekono ekta true ase kina 

print(np.all(greater_than)) 
print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


### SORTING

In [41]:
#inplace

x = np.array([ 10 , 8 , 16 , 100 ])
z = x.copy()
print(z)

z.sort()
print(z)

# copy sorting

print(x)
sort_arr = np.sort(x) 
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [43]:
# 2d array sorting 

mat = np.array([[10,3,5],[8,4,9]])
print(mat)

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[10  3  5]
 [ 8  4  9]]
[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### SEARCHING

In [44]:
# np.where( condition , x , y ) if true x , otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array 
print(arr)

(array([1]),)
[ 10   0  16 100]


In [47]:
mat = np.array([[10,3,5],[8,4,9]])
print(mat)

index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [48]:
x = np.array([ 10, 100, 8, 16, 100 ])

maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


### COUNTING IN NDARRAY

In [50]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

print()
unique_value,count = np.unique(a,return_counts=True)
print(unique_value) 
print(count)

[ 4 33 84 26 15 29 97 88 54 78 51 68  9 41 76 43 18  9 60 19 69 20 32 30
 72 42 44 28 57 65  8  3 27 21 65 29 88 19 23 57 11 24 73 45 94 95 27 92
 86 48 52 29 10 88 49 32 65 62 69 87 32 47 31 83 96 12 80 52  5 63 62 23
 50 29 62 91 56 74 23 30  4 66 39 85 71 50 77 15 59 89 41 82 67 26 80 11
 80 33 76 21]
1

[ 3  4  5  8  9 10 11 12 15 18 19 20 21 23 24 26 27 28 29 30 31 32 33 39
 41 42 43 44 45 47 48 49 50 51 52 54 56 57 59 60 62 63 65 66 67 68 69 71
 72 73 74 76 77 78 80 82 83 84 85 86 87 88 89 91 92 94 95 96 97]
[1 2 1 1 2 1 2 1 2 1 2 1 2 3 1 2 2 1 4 2 1 3 2 1 2 1 1 1 1 1 1 1 2 1 2 1 1
 2 1 1 3 1 3 1 1 1 2 1 1 1 1 2 1 1 3 1 1 1 1 1 1 3 1 1 1 1 1 1 1]


### STATISTICAL FUNCTION

In [51]:
#data load 

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)
print(data) 

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [52]:
# statistics  
sci_marks = data[::,1:2]
print(sci_marks.T)

max_sci_marks = np.max(sci_marks)
print(max_sci_marks)

min_sci_marks = np.min(sci_marks)
print(min_sci_marks)

average_sci_marks = np.mean(sci_marks)
print(average_sci_marks)

median_sci_marks = np.median(sci_marks)
print(median_sci_marks) 

# standard deviation
std_sci_marks = np.std(sci_marks)
print(std_sci_marks)

[[85. 67. 92. 52. 75. 90. 60. 57. 89. 70. 69. 82. 64. 78. 93. 71. 79. 86.
  63. 97.]]
97.0
52.0
75.95
76.5
12.804198530169703


In [54]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])
print(data)

correlation = np.corrcoef(data)
print("Correlation Matrix:\n", correlation)

[[ 2  4  5  7  8]
 [65 75 78 88 92]]
Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


### LINEAR ALGEBRA

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe 
dot_product = np.dot(A,B)
print(dot_product)

# trace 
print(np.trace(B)) 

[[ 58  64]
 [139 154]]
17


In [57]:
sq_mat = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                ])

det_of_sq = np.linalg.det(sq_mat)
rank_sq = np.linalg.matrix_rank(sq_mat)
print(det_of_sq)
print(rank_sq)

-9.51619735392994e-16
2


In [60]:
print(np.sin(np.pi/2))

A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

1.0
[[19 22]
 [43 50]]
