### NUMPY

In [2]:
# List e simd kaj korena
arr = [1,2,3]
print( arr * 5 )
arr = [ x*5 for x in arr] 
print(arr)

#ndarray te kore
import numpy as np 
arr1 = np.array([1,2,3]) 
arr1 = arr1 * 5
print(arr1)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]
[ 5 10 15]


### NDARRAY

In [1]:
import numpy as np 

# 1d array 
arr1 = np.array([1,2,3,4,5])

# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array 
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor
     [[1,2,3], # row1
      [4,5,6]  ], #row2  

    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  
])

print(arr1)
print()
print(arr2)
print()
print(arr3)

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### ATTRIBUTES

In [2]:
# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print()

#shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 

print()

#data type 
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print()

#size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3

(5,)
(2, 3)
(3, 2, 3)

int64
int64
int64

5
6
18


### DATA TYPE

In [4]:
arr = np.array([1, 2, 3]) 
print(arr.dtype)

arr = np.array([1.5, 2.4, 3.2]) 
print(arr.dtype)

#upcasting
arr = np.array([1, 2, 3.2]) 
# upcasted to float 
print(arr.dtype) 

#upcasted to string
arr = np.array([1, 2, 3.2, 'hello']) 
print(arr.dtype) 

arr = np.array([1, True, 3.25, 'hello']) # can't keep a list in it
print(arr.dtype)

int64
float64
float64
<U32
<U32


### SELECTING DATA TYPE

In [6]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)

#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64) 

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

### NDARRAY FROM EXISTING DATA

In [5]:
# LIST
lst = [10,20,30,40 , 40.5] 
arr = np.array(lst) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 

print()

mixed_lst = [10, True, 'Hello']
arr = np.array(mixed_lst, dtype = 'U32') 
print(arr) 
print(type(arr)) 
print(arr.dtype) 

print()

matrix = [ [1,2,3], #row1
           [4,5,6] #row2
        ]
arr = np.array(matrix) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64

['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U32

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [7]:
#TUPLE
tpl = (10,20,30) 
arr = np.array(tpl,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype) 
arr = arr.astype(np.int16) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int32
int16
(3,)
1


In [17]:
#SET
st = { 1, 2, 3 }
arr = np.array(st) #takes whole set as object
# print(arr.dtype) 
# arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)

print()

arr = np.array(list(st)) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

{1, 2, 3}
<class 'numpy.ndarray'>
object
()
0

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [19]:
#DICTIONARY 
dc = { 'a' : 10 , 'b' : 20, 'c' : 30 }
keys = dc.keys()
values = dc.values()
items = dc.items()

#keys to ndarray
arr = np.array(list(keys))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

print()

#values to ndarray
arr = np.array(list(values))
print(arr) 
arr = arr.astype(np.int16)
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

print()

#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


### NDARRAY FROM SCRATCH

In [8]:
# np.zeros(dimension, datatype)
arr = np.zeros((2,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
print()

arr = np.zeros_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [9]:
#np.ones(dimensions, datatype)
arr = np.ones((3,4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
print()

arr = np.ones_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [29]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
print()

arr = np.empty_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape)

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [31]:
#np.full 
arr = np.full((4,3),np.inf)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
print()

arr = np.full_like(arr3,np.inf,dtype=np.float64) 
print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


### NDARRAY FROM RANDOM VALUES

In [32]:
# np.random.rand(shape) 
arr = np.random.rand(2,3) #random values 0 -> 1 
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.99052368 0.44362879 0.97051634]
 [0.86976303 0.79386219 0.47679393]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [33]:
# np.random.randint(start,end,shape) 
arr = np.random.randint(1, 10, (2,3))  
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[8 8 8]
 [6 7 9]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [34]:
# np.random.uniform(start,end,shape) 
arr = np.random.uniform(50, 100, (3,3,4)) #float values   
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[74.13699226 82.21724014 60.25440274 65.73973021]
  [97.58717718 74.3900999  69.76591471 89.49942709]
  [51.93502911 53.01208102 89.70561737 55.24635605]]

 [[88.00840472 90.17669557 68.77574624 99.07479597]
  [64.19794857 52.61438531 51.7436893  74.83839747]
  [68.51844399 56.30701073 55.67836307 61.41138973]]

 [[70.05848245 50.69061467 96.74926969 97.43383087]
  [96.74034529 86.7808504  97.84616044 99.58473101]
  [65.35760348 95.94553182 70.28691876 63.06121466]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


### NDARRAY FROM RANGE

In [35]:
# np.arange(first , end, step) -> similar to range function 
arr = np.arange(1 , 10, 1)
mat = arr.reshape(3,3) 
print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [36]:
# np.linspace(start , end(included), koita) 
arr = np.linspace(0, 4, 6)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [38]:
# np.logspace(start , end(included) , koita , base) 
arr = np.logspace(0, 4, 6, base = 2) #[2^0, 2^0.8, 2^1.6, 2^2.4, 2^3.2, 2^4]
print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


### MATRIX FOR LINEAR ALGEBRA

In [39]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [10]:
# identity matrix 
identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)
print()

# np.eye(row, column, k) 
mat = np.eye(3,4)        
print(mat)

mat = np.eye(3,4,1)      # k = +1 -> right e jay
print(mat)               # k = -1 -> left e jay

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### INDEXING AND SLICING

In [61]:
#indexing 
#print(arr1)
#print(arr2)

# 1d array 
arr1 = np.array([1,2,3,4,5])

# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#arr1[2] = 100 
#print(arr1)
arr2[0][2]= 100
print(arr2)

[[  1   2 100]
 [  4   5   6]]


In [62]:
#slicing 
#1d = arr[start:end:step] 

arr1_mod = arr1[1:4].copy() #eta korle arr1 er ekta independent copy create hoy
arr1[1] = 2                 #arr1_mod1 change korle arr1 change hobe na

arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [63]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]
# print(arr2) 

#getting a row
row_0 = arr2[0:1 ,]
row_1= arr2[1: , ]
print(row_0)
print(row_1)
print()

#getting a column 
col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]
print(col_0)
print(col_1)
print()

#getting a portion 
portion = arr2[:: , 0:2] 
print(portion)

[[  1   2 100]]
[[4 5 6]]

[[1]
 [4]]
[[2]
 [5]]

[[1 2]
 [4 5]]


### ADVANCED INDEXING AND ITERATION

In [64]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 
values = lst[[0,3,1]]
print(values)

[10 40 20]


In [72]:
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>2])
print(arr2[arr2<2])

arr2[arr2>2] = 0 
print(arr2)

[[1 2 3]
 [4 5 6]]
[2 6]
[3 4 5 6]
[1]
[[1 2 0]
 [0 0 0]]


In [73]:
arr  = np.array([[10,20,30], 
                 [100,200,300]])

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
