## PRACTICE DAY 11.5

#### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

#### 2 . Create:
#### an array of zeros of shape (3,3)

#### an array of ones of shape (2,5)

#### an array filled with 7

#### 3 . Create an array of even numbers between 10 and 50 using arange.

#### 4 . Create a 4×4 matrix from 0–15. Then , extract:
#### the first row

#### the last column

#### a 2×2 subarray from the center

#### 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.
#### 6 . Given two arrays A and B, compute:
#### (A + B) / 2

#### A^2 + B^2


In [1]:
import numpy as np
#numpy chara cholei na :)

In [6]:
#1. Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.
arr_1D = np.random.randint(1, 10, (5, ))
print(arr_1D)
print(arr_1D.ndim)
print(arr_1D.shape)
print()

arr_2D = np.random.randint(1, 10, (3, 2))
print(arr_2D)
print(arr_2D.ndim)
print(arr_2D.shape)
print()

arr_3D = np.random.randint(1, 10, (2, 4, 3))
print(arr_3D)
print(arr_3D.ndim)
print(arr_3D.shape)

[5 5 4 8 5]
1
(5,)

[[4 3]
 [6 5]
 [3 8]]
2
(3, 2)

[[[7 5 7]
  [8 5 9]
  [6 7 4]
  [5 3 9]]

 [[9 2 9]
  [1 4 5]
  [3 4 9]
  [5 9 7]]]
3
(2, 4, 3)


In [11]:
#2. Create:
#an array of zeros of shape (3,3)
#an array of ones of shape (2,5)
#an array filled with 7

arr_0 = np.zeros((3,3), dtype="int16")
print(arr_0)
#print(arr_0.dtype)

print()
arr_1 = np.ones((2,5), dtype="int8")
print(arr_1)
#print(arr_1.dtype)

print()
arr_7 = np.full((3,4,3), 7, dtype="int32")
print(arr_7)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1 1 1]
 [1 1 1 1 1]]

[[[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]]


In [14]:
#3. Create an array of even numbers between 10 and 50 using arange.
even = np.arange(10, 52, 2)
print(even)

even2 = np.linspace(10, 50, 21)
print(even2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]


In [18]:
#4. Create a 4×4 matrix from 0–15. Then, extract:
#the first row
#the last column
#a 2×2 subarray from the center
mat_4 = np.random.randint(0, 15, (4,4))
print(mat_4)
print()

row_1 = mat_4[0:1, ]
row_2 = mat_4[::, 3:]
sub_arr = mat_4[1:3, 1:3]
print(row_1)
print(row_2)
print(sub_arr)

[[ 2 14 13 11]
 [ 3  6  6  4]
 [ 9  4  2  7]
 [ 5  2  0  1]]

[[ 2 14 13 11]]
[[11]
 [ 4]
 [ 7]
 [ 1]]
[[6 6]
 [4 2]]


In [19]:
#5. Add a 1D array [1,2,3] to each row of a 3×3 matrix.
mat_3 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr_1 = np.array([1, 2, 3])
ans = mat_3 + arr_1
print(ans)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [21]:
#6. Given two arrays A and B, compute:
#(A + B) / 2
#A**2 + B**2
A = np.array([[3, 5, 4],
              [7, 2, 6]
             ])
B = np.array([[15, 12, 17],
              [11, 14, 18]
             ])
ans1 = A + B
ans1 = ans1/2
print(ans1)

ans2 = A**2 + B**2
print(ans2)

[[ 9.   8.5 10.5]
 [ 9.   8.  12. ]]
[[234 169 305]
 [170 200 360]]
